name: Publish

on:

    pull_request:
        types: [closed]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: rm -r -f ./dist
      - run: npm ci      
      - run: npm run build      
      - run: node .github/workflows/set-version-number.js	  
      - run: cp -a ./build/js/. ./dist/
      - run: rm ./dist/*.dev.*
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}