name: Publish

on:
    pull_request:
        types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci      

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: node .github/workflows/set-version-number.js	  
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}